### ISSUE TITLE
The MLB changed how we have to format our base URLs

### ISSUE THREAD

**Issue by Mpellet771** [cpsievert/pitchRx#59] opened 2018-02-17 05:05 UTC
Thank you for writing this package. However, for 2017 on, the url can't be resolved if the base url has the slash after the DAy_## section, like this:

http://gd2.mlb.com/components/game/mlb/year_2017/month_06/day_14/

Using that last slash gets you an error code. It must be removed from the base url and added to the gid url.

See here for the explanation on one of the Python forums: https://www.reddit.com/r/Sabermetrics/comments/7v07ax/mlb_gameday_data_sites_down_went_private/

**Comment by cpsievert** [comment] 2018-02-20 15:20
Duplicate of #57

**Closed by cpsievert** 2018-02-20 15:20 UTC
